<a href="https://colab.research.google.com/github/tashubansal/Data-science/blob/main/20july(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
n1=np.array([[1,2,3],[6,3,4],[9,1,2],[0,1,3]])
print(n1)

[[1 2 3]
 [6 3 4]
 [9 1 2]
 [0 1 3]]


In [ ]:
print(n1.shape)

(4, 3)


In [ ]:
#Slicing
#1.Printing all rows and first column
print(n1[:,0])

#2.Printing all columns and first row
print(n1[0,:])

[1 6 9 0]
[1 2 3]


In [ ]:
n2=np.array([[45,23,78,34],[35,12,9,6],[67,4,98,12],[43,67,34,2]])
print(n2)
#printing slicing range from second element of second row to fourth element of third row.
# print(n2[[2][1]:[3][3]])
# print(n2[2][1],[3][3])

[[45 23 78 34]
 [35 12  9  6]
 [67  4 98 12]
 [43 67 34  2]]


IndexError: ignored

In [ ]:
#Flattened the array
n2.ravel()

array([45, 23, 78, 34, 35, 12,  9,  6, 67,  4, 98, 12, 43, 67, 34,  2])

In [ ]:
# T returns the transpose of the array i.e. row becomes the column and column becomes the row
n2.T

array([[45, 35, 67, 43],
       [23, 12,  4, 67],
       [78,  9, 98, 34],
       [34,  6, 12,  2]])

In [ ]:
B=np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[12,13,14,15],[16,17,18,19],[20,21,22,23]]])

In [ ]:
print(B)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
#when we have 2 dimensional arrays in one array object then B[:-dimensions,:-rows,:-columns]
print(B[0,2,1])


9


In [ ]:
#print the first element of each row of both dimensions
print(B[:,:,0])

[[ 0  4  8]
 [12 16 20]]


In [ ]:
#print the last element of first row of first dimension.
print(B[0,0,3])
#print the last element of first row of second dimension.
print(B[1,0,3])

3
15


In [ ]:
#print all elements of second dimension
print(B[1,:,:])

#The dots(...) represents as many as colons as needed to produce a complete indexing tuple.
print(B[1,...]) #represents second dimension and all rows + columns
print(B[...,1]) #represents all dimensions all rows first column

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 1  5  9]
 [13 17 21]]


In [ ]:
for i in B.flat:
  print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [ ]:
print(B.flat)

In [ ]:
#Slice is a view-->It means changing the value in slice of array will change the original array
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr1=arr[1:2,1:]
#arr1 is a two dimensional array
print(arr1)

[[6 7 8]]


In [ ]:
arr1[0][1]=55
print(arr1)

[[ 6 55  8]]


In [ ]:
#when the value in the slice has been changed the original value will also make chnages
print(arr)

[[ 1  2  3  4]
 [ 5  6 55  8]
 [ 9 10 11 12]]


RANDOM NUMBERS USING NUMPY

In [ ]:
from numpy import random

In [ ]:
#Random module has many functions like randit,rand,random
#rand method will generate float number from 0 to 1
x=np.random.random()
print(x)
#there is no difference between random and rand
y=np.random.rand()
print(y)
#to generate integer between 0 to the number given as argument
z=np.random.randint(4)
print(z)


#The output of the above code will be different every time.

0.41809072894066857
0.7306421084497541
3


In [ ]:
#Random module is also used to generate the array.
arr=np.random.random(size=(2,1)) #2 rows 1 column
print(arr)

arr2=np.random.random(size=5)
print(arr2)
print(type(arr2))

[[0.56485316]
 [0.84062694]]
[0.56174406 0.27399169 0.48006598 0.19296825 0.44388287]
<class 'numpy.ndarray'>


In [ ]:
arr3=np.random.randint(100,size=(5,5))
print(arr3)

[[ 2  3 68 12 29]
 [60 19 72 69 27]
 [ 5 45 92 10 14]
 [54 50 23 22 52]
 [47 43 81 57 46]]


In [ ]:
a=np.floor(10*np.random.random((2,2)))
b=np.floor(20*np.random.random((2,2)))
print(a)
print(b)

[[7. 3.]
 [5. 2.]]
[[ 4.  9.]
 [ 1. 13.]]


In [ ]:
np.hstack((a,b))

array([[ 7.,  3.,  4.,  9.],
       [ 5.,  2.,  1., 13.]])

In [ ]:
np.vstack((a,b))

array([[ 7.,  3.],
       [ 5.,  2.],
       [ 4.,  9.],
       [ 1., 13.]])